---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    name: postgres-deployment
    author: intelliqit
spec:
  replicas: 2
  selector:
    matchLabels:
      name: postgres-deployment
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-deployment
    spec:
      containers:
        - name: postgresdb
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: user
...
