---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
 labels:
  type: proxy
  author: intelliqit
spec:
 replicas: 3
 selector:
  matchLabels:
   type: proxy
 template:
  metadata:
   name: ngonx-pod
   labels:
    type: proxy
  spec:
   containers:
    - name: nginx
      image: nginx
      ports:
       - containerPort: 80
         hostPort: 9090
...

