--- 
apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
 labels:
  author: intelliqit
  type: proxy1
spec:
 replicas: 3
 selector:
  matchLabels:
   type: proxy1
 template:
  metadata:
   name: nginx-pod
   labels:
    type: proxy1
  spec:
   containers:
    - name: nginx
      image: nginx
      ports:
       - containerPort: 80
         hostPort: 8080
...
