---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: httpdd-deployment
 labels:
  type: webserver
spec:
 replicas: 2
 selector:
  matchLabels:
   type: webserver
 template:
  metadata:
   name: httpd-pod
   labels:
    type: webserver
  spec:
   containers:
    - name: mywebserver
      image: httpd
...
