---
apiVersion: v1
kind: Pod
metadata:
 name: ghost-pod
 namespace: test-ns
 labels:
  author: intelliqit
spec:
 containers:
  - name: ghost
    image: ghost
    ports:
     - containerPort: 2368
       hostPort: 8080
...

