---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: tomcat-rs
 labels:
  author: intelliqit
  type: appserver
spec:
 replicas: 4
 selector:
  matchLabels:
   type: appserver
 template:
  metadata:
   name: tomcat-pod
   labels:
    type: appserver
  spec:
   containers:
    - name: mytomcat
      image: tomcat
      ports:
       - containerPort: 8080
         hostPort: 9090
...
