---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
 labels:
  type: proxyserver
  author: krishna
spec:
 replicas: 3
 selector:
  matchLabels:
   type: proxyserver
 template:
  metadata:
   name: nginx-pod
   labels:
    type: proxyserver
  spec:
   containers:
    - name: nginx
      image: nginx
      ports:
       - containerPort: 8080
         hostPort: 8080
...
