---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    author: krishna
spec:
  containers:
    - name: nginx
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: slave_id
                operator: In
                values:
                  - slave1
