---
apiVersion: v1
kind: Pod
metadata:
 name: postgres-pod
 labels:
  type: db
  author: krishna
spec:
 containers:
  - name: mydb
    image: postgres
    env:
     - name: POSTGRES_PASSWORD
       valueFrom: 
        secretKeyRef:
         name: postgres-secrets
         key: password
     - name: POSTGRES_USER
       valueFrom:
        secretKeyRef:
         name: postgres-secrets
         key: user
     - name: POSTGRES_DB
       valueFrom:
        secretKeyRef:
         name: postgres-secrets
         key: db

...
