---
apiVersion: v1
kind: ReplicationController
metadata:
 name: httpd-rc
 labels:
  author: krishna
spec:
 replicas: 3
 template:
  metadata:
   name: httpd-pod
   labels:
    author: krishna
  spec: 
   containers:
    - name: myhttpd
      image: httpd
      ports:
       - containerPort: 8080
         hostPort: 8080
...
