---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    author: intelliqit
spec:
  containers:
    - name: nginx
      image: nginx
  tolerations:
    - key: "key1"
      operator: "Exists"
      effect: "NoSchedule"
